// packages/app/app/components/Slide.tsx
import clsx from "clsx";
import type React from "react";

export const Slide: React.FC<{
  isActive: boolean;
  item: string;
}> = ({
  isActive,
  item,
}) => {
    const parentClass = clsx("w-screen h-screen p-6 box-border print:block print:visible print:p-0", isActive ? 'block' : 'hidden');
    return (
      <div className={parentClass}>
        <div className='bg-white max-h-full max-w-full aspect-video h-auto w-auto print:h-full print:w-full' dangerouslySetInnerHTML={{ __html: item }} />
      </div>
    )
  };

// packages/app/src/components/Slide.svelte
<script lang="ts">
	export let item = '';
	export let isActive: boolean = false;
</script>

<div
	class="box-border h-screen w-screen p-6 print:visible print:block print:p-0"
	class:block={isActive}
	class:hidden={!isActive}
>
	<div class="aspect-video h-auto max-h-full w-auto max-w-full bg-white print:h-full print:w-full">
		{@html item}
	</div>
</div>
